import asyncio, json
from datetime import datetime
from io import BytesIO
from zipfile import ZipFile, ZIP_DEFLATED
from sqlalchemy.orm import Session
from app.models import Agent, Execution, Log, Project
AGENTS = [
("Orchestrator Agent", "Coordinate the autonomous software team and synthesize decisions."),
("Product Manager Agent", "Define users, requirements, scope, milestones, and success metrics."),
("Architect Agent", "Design system architecture, services, integrations, and non-functional requirements."),
("Backend Developer Agent", "Plan APIs, authentication, business logic, and deployment details."),
("Frontend Developer Agent", "Plan responsive UI, routes, components, and state management."),
("Database Designer Agent", "Design normalized schema, indexes, migrations, and data lifecycle."),
("QA Tester Agent", "Create test strategy, acceptance criteria, and quality gates."),
("Documentation Agent", "Write project README, setup guide, and operational documentation."),
]
def seed_agents(db: Session, project: Project):
    if project.agents: return
    for i,(role,prompt) in enumerate(AGENTS): db.add(Agent(project_id=project.id, role=role, prompt=prompt, position=i))
    db.commit(); db.refresh(project)
def log(db, project_id, message, agent_id=None, level="info"):
    db.add(Log(project_id=project_id, agent_id=agent_id, message=message, level=level)); db.commit()
def deterministic_output(role, idea, context):
    return f"## {role}\n\nFor **{idea}**, deliver a secure, scalable product. Context from prior agents: {context[-600:] or 'none yet'}.\n\n- Primary deliverable: clear implementation guidance.\n- Production concern: observability, auth, testing, and deployability.\n- Risk control: incremental milestones with review gates."
def build_files(project: Project):
    slug = project.name.lower().replace(' ', '-')
    return {
        f"{slug}/README.md": f"# {project.name}\n\n{project.documentation}\n",
        f"{slug}/SPECIFICATION.md": project.documentation,
        f"{slug}/docs/architecture.md": next((a.output for a in project.agents if a.role.startswith('Architect')), ''),
        f"{slug}/docs/testing.md": next((a.output for a in project.agents if a.role.startswith('QA')), ''),
        f"{slug}/src/app.py": "print('Generated by AgentForge AI')\n",
    }
async def run_project(db_factory, project_id: int):
    db = db_factory()
    try:
        project = db.get(Project, project_id); seed_agents(db, project)
        execution = Execution(project_id=project_id, status="running", started_at=datetime.utcnow()); db.add(execution)
        project.status = "running"; db.commit(); log(db, project_id, "Execution started")
        context = ""
        for agent in project.agents:
            agent.status = "running"; db.commit(); log(db, project_id, f"{agent.role} started", agent.id)
            await asyncio.sleep(0.4)
            agent.output = deterministic_output(agent.role, project.idea, context)
            agent.memory = {"inputs": project.idea, "context_tokens": len(context.split()), "completed_at": datetime.utcnow().isoformat()}
            agent.status = "completed"; context += "\n" + agent.output
            db.commit(); log(db, project_id, f"{agent.role} completed", agent.id)
        project.documentation = f"# {project.name}\n\n## Idea\n{project.idea}\n\n## Agent Plan\n" + "\n".join(a.output for a in project.agents)
        project.generated_files = build_files(project); project.status = "completed"
        execution.status = "completed"; execution.completed_at = datetime.utcnow(); db.commit(); log(db, project_id, "Execution completed")
    except Exception as exc:
        project = db.get(Project, project_id)
        if project: project.status = "failed"
        db.commit(); log(db, project_id, f"Execution failed: {exc}", level="error")
    finally: db.close()
def zip_project(project: Project):
    buf = BytesIO()
    with ZipFile(buf, 'w', ZIP_DEFLATED) as zf:
        for path, content in (project.generated_files or {}).items(): zf.writestr(path, content)
    buf.seek(0); return buf
